### PR TITLE
Add Laravel 7.x Support

### PR DESCRIPTION
**Pull request by hmoradian**
Add Laravel version from 5.4 up to 7.x support

### CODE REVIEW

**Comment by niekappartmedia** [comment]
@streamtw Could you please merge this so Laravel 7.3 is suported?

**Comment by hmoradian** [comment]
> @streamtw Could you please merge this so Laravel 7.3 is suported?

I have already requested, but not done so far!

**Comment by arshiyaolka** [comment]
Why not release a new version for the latest version of Laravel?

Please

**Comment by olipiskandar** [comment]
we need update. bump this PR

**Comment by hmoradian** [comment]
I'm waiting for confirm and merge my pull request by UniSharp!

**Comment by hmoradian** [comment]
This version of package not still to stable for Laravel 7.x :(

**Pull request closed without merging**
