### PR TITLE
fix(Upload): fix input name

### PR DESCRIPTION
**Pull request by welcoMattic**

### CODE REVIEW

**Comment by welcoMattic** [comment]
It fix upload through original file input of ckeditor (tab Upload), I think we should change the name of file input inside the filemanage, to match it to the ckeditor's one.

Are you ok? I'll PR soon

**Comment by g0110280** [comment]
Just found that upload function in "Upload" tab does not work.
It with be done next week, and fixing input name will be the first step.
Thank you again.

**Comment by welcoMattic** [comment]
Yes, it fails because of csrf_token not provided.
A quick hack is to set the value of csrf_token inside a `meta` tag with `content` attribute that contains the token, and get it with a basic js selector and inject it on your ckeditor config (fileupload routes) named as `_token`.

Example:

`var csrfToken = $('meta[name="csrf-token"]').attr('content');`
...
`filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + csrfToken,`

**Comment by g0110280** [comment]
I just fixed csrf issue.
Please update to dev-master.

**Pull request merged**
