### PR TITLE
Showing message to user when file successfully uploaded

### PR DESCRIPTION
**Pull request by abdi42**
When uploading images, as an admin user I would like to know if the upload was successful or not.

### CODE REVIEW

**Comment by g0110280** [comment]
Thank you @abdi42 .

**Comment by gwleuverink** [comment]
May I suggest an alternative approach? Since this is merged there is no way to opt-out of this feature. I don't want my clients to click to dismiss a popup every time a file has uploaded. Especially since a error message pops up when the upload fails.

What do you think about writing up a feature that uses the events you can listen to to modify the response and add an optional message propery. If the property exists, a popup message is show.

Besides acheiving what @abdi42 needs it also enhances the flexibility of all events that are raised.

What do you guys think about this?

**Comment by g0110280** [comment]
@gwleuverink I got your point. Maybe we can use [alerts](http://getbootstrap.com/components/#alerts-examples) as alternative. How do you think?

**Comment by gwleuverink** [comment]
@g0110280 That sounds great 👍 Alerts seem perfect since it allows the user to simply ignore it and move on. The error messages and such will still be displayed in a modal right?

**Pull request merged**
