### PR TITLE
add support for the Hebrew language

### PR DESCRIPTION
**Pull request by kfirba**
Hey.

I've seen that there are several translation but not a Hebrew one.
I thought it would be nice if there was one.

Please do note, Hebrew is an RTL language. I didn't see any way to specify that so I guess the package is LTR only. The hebrew is still fine. 
I suppose Hebrew speakers would prefer the LTR Hebrew version than the English version.

I didn't change the README file, I will let you do that.

### CODE REVIEW

**Comment by youchenlee** [comment]
Thank you @kfirba 
As I know the browsers will automatically set the page (all the UI layouts especially forms and texts) to RTL when the browser (or HTML) lang is set to Hebrew. 
Please let me know what part of the laravel-filemanger source code is blocking it from changing to RTL.

**Comment by youchenlee** [comment]
We will update the README file before the next release.

**Comment by kfirba** [comment]
@youchenlee oh well, I just used the routes that were supplied with the package without editing them. I will try to edit the lang attribute on the layout page to `he` and will let you know.

**Comment by kfirba** [comment]
@youchenlee is the package using the conditional RTL bootstrap package? I remember running across it a while back

**Comment by kfirba** [comment]
@youchenlee I just checked how it looks with `dir="rtl"` and there is only one critical issue. The table headers in list view aren't aligned. It should align them to the right, otherwise it looks off.

This can be solved by adding a simple CSS rule:

```
html[dir="rtl"] thead th {
    text-align: right;
}
```

I wonder how come it's not doing that by default..

**Comment by youchenlee** [comment]
@kfirba 
It's hard for me to test a RTL layout on my computer. 
Whatever you feel it's right to do about RTL and does not affect other LTR users,  please send us a PR for it (and attached some screenshots for both RTL and LTR if possible). Thanks. 

I will merge this Hebrew translation PR first. It will be closed but we can keep discussing here.

**Comment by kfirba** [comment]
@youchenlee Actually, there is a much simpler solution which works perfectly fine. What you can do is pull in Bootstrap-RLT package and this will make sure everything looks just great. You can use [moreteza's extension](https://github.com/morteza/bootstrap-rtl) or use the [on-demand package](https://github.com/bright/bootstrap-rtl). The on-demand package will use the LTR styling by default and will only use the RTL styling if the `html` tag has `dir="rtl"` which is very useful. Unlike Morteza's packge, the on-demand package seems like it's not getting updated very frequently.

Another option will be to have the RTL file in the public folder and just add a some lines in the documentation that tell the user to add the the CSS file to the view when needed.

What do you think?

**Pull request merged**
