### PR TITLE
Added Italian language support

### PR DESCRIPTION
**Pull request by arturmamedov**

### CODE REVIEW

**Comment by Andicot** [comment]
Can you add Italian language please. 
[it.zip](https://github.com/UniSharp/laravel-filemanager/files/2250838/it.zip)

**Comment by g0110280** [comment]
Thank you @arturmamedov !

**Comment by arturmamedov** [comment]
Thank u @g0110280 great work!!!!

**Comment by arturmamedov** [comment]
And for the master branch? You want a separated pull-request or you merge `v1` into `master` later?

**Comment by g0110280** [comment]
I will cherry-pick this commit into `master` branch. Thank you for the advice as well.

**Pull request merged**
