### PR TITLE
Update LfmHelpers.php

### PR DESCRIPTION
**Pull request by B-GH**
fix infector bug

### CODE REVIEW

**Comment by youchenlee** [comment]
Thank you @B-GH 
It looks like the behavior of `str_singular(null);` has changes in newer laravel. 
Would you please modify the PR to use the second parameter of `request()` for making it shorter?

```
request('type', '');
```

**Comment by B-GH** [comment]
Done.

**Comment by youchenlee** [comment]
Thank you very much!

**Comment by youchenlee** [comment]
Looks like there's some conflicts. I will merge it manually later when I reach my computer.

**Comment by youchenlee** [comment]
Done! thanks.

**Comment by B-GH** [comment]
your welcome

**Pull request closed without merging**
