### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by amin101**
fixed image url for window users
added independent filemanager usage capability

### CODE REVIEW

**Comment by youchenlee** [comment]
@amin101 looks awesome! Thanks.
I will merge it ASAP after few tests.

Just realize that our previous commit breaks windows users. Sorry for that mistake.

**Comment by amin101** [comment]
I'm making some small changes plus adding fa/persian language file . I'll send a new PR soon!

**Comment by youchenlee** [comment]
@amin101 okay! looking forward to it!

**Comment by youchenlee** [comment]
:+1: :+1: :+1:

**Pull request merged**
