### PR TITLE
Thumbs

### PR DESCRIPTION
**Pull request by iankov**
Added config lfm.thumb_mimetypes to define which image types should create thumbnails automatically. This config was added to let user define which file type shoud have a thumbnail. Also you can make this config array empty, so thumbnails would never be created.

removeDuplicateSlash function was rebuild to replace 2 or more slashes by one. Original function was replacing only 2 slashes by one, like so: "mydir///my-subdir" would return "mydir//my-subdir". 

Added animation loader. Very useful feature when you are trying to open directory with many files inside. It could take long time like 5-10 seconds to open that directory. Hard to understand what's going on if you have no loader. You just click some folder and nothing happens.

### CODE REVIEW

**Comment by gwleuverink** [comment]
Really like the loader svg proposal! 

Have you thought about creating a excluded_thumbs_mimetypes config property instead so users don't have to add new mimetypes twice?

Just a thought tough, with a little developer happiness in mind :)

**Comment by iankov** [comment]
Okay, I can make config with excluded_mimes. I would also add a new config key like "create_thumbnails" (true, false) to make it possible to disable thumbnail creation. That's the main reason I made the config in the first place. I dont want filemanager to create any thumbnails on the server.

**Comment by gwleuverink** [comment]
Maybe the maintainers of the package don't agree with me, so no rush refactoring. What do you think @g0110280 @youchenlee ?

**Comment by youchenlee** [comment]
Thank you @iankov and @gwleuverink 

How about use both `raster_mimetypes = [...]` and `should_create_thumbnails = true/false` together?

The reason of naming it `raster_mimetypes` instead of `thumbs_mimetypes` is that [CropController](https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/CropController.php) and [ResizeController](https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/ResizeController.php) may also need this config later.

Personally, I prefer positive configs, I think writing new mime-types twice is okay, the two configs `valid_image_mimetypes` and `raster_mimetypes` are eventually for different purposes.

And I agree that some might need to crop/resize images manually, without automatically making the thumbnails. So `should_create_thumbnails = true/false` (or `create_thumbnails = true/false`)  is reasonable to co-exist.

@iankov please feel free to do whatever you think is right. I will merge anything making a progress.

@gwleuverink BTW, thank you for always helping us out. Would you like to be the collaborator of this repo? I am very happy to see it.

**Comment by iankov** [comment]
Added raster_mimetypes and should_create_thumbnails config as discussed.

Also added create_file_mode and create_folder_mode.

Added new actions in the list-view. These are the same actions that are available with grid-view, but weren't available in a list-view. Also added "title=" attributes to action links to show a hint on hover

**Comment by youchenlee** [comment]
@iankov Thank you. I'll check it tomorrow.

**Comment by gwleuverink** [comment]
@youchenlee Sorry for the late reply. It would be my privilege. I wouldn't be able to contribute as steadily as you guys do tough (you do so much work!). But if you'll have me I'm happy to pitch in!

**Comment by youchenlee** [comment]
Merged! Thank you @iankov. Sorry for my late.

**Pull request merged**
