### PR TITLE
Add drag and drop upload using dropzone.js

### PR DESCRIPTION
**Pull request by harimayco**
[](https://postimg.org/image/llfungf6t/)

### CODE REVIEW

**Comment by youchenlee** [comment]
Love this PR! Thank you @harimayco

**Comment by g0110280** [comment]
Thank you @harimayco. This is awsome!!

**Comment by ibnuh** [comment]
Any documentation how to use this?

**Comment by youchenlee** [comment]
@ibnuh I think the video explains everything.
https://postimg.org/image/llfungf6t/ (by @harimayco)

**Comment by ibnuh** [comment]
Yes, thank you very much! @youchenlee @harimayco. It works now

Just started using laravel for a week and I found it really awesome! Especially with this laravel-filemanager plugin.

**Pull request merged**
