### PR TITLE
Create an option to perform chmod

### PR DESCRIPTION
**Pull request by KJLKurt**
With my host I don't have access to change file permissions.   I would like to be able to upload files without getting an error because of chmod permission denied.

### CODE REVIEW

**Comment by KJLKurt** [comment]
Possibly related to #403 as version 1.8.1 the code tried to change permissions before it moved the file.  As of 1.8.2 it will move the file before trying to perform changes in file permissions.

**Comment by youchenlee** [comment]
Hi @KJLKurt , it looks very nice. Thank you

How about adding a prefix 'should_' to make it more like a boolean attribute?
For example: 'should_change_file_mode'. 

Would you please help with it?

**Comment by KJLKurt** [comment]
Hello @youchenlee I have made the requested changes.

**Comment by youchenlee** [comment]
Thank you @KJLKurt

**Pull request merged**
